Updated git shell commands scripts, and added a new one
Also debugged make update/install commands, and jekyll_usermod.sh script

diff --git a/git_shell_commands/bundle-install b/git_shell_commands/bundle-install
--- a/git_shell_commands/bundle-install
+++ b/git_shell_commands/bundle-install
@@ -6,7 +6,6 @@ while [[ -h "${__SOURCE__}" ]]; do
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
-__PATH__="${__DIR__}/${__NAME__}"
 __AUTHOR__='S0AndS0'
 __DESCRIPTION__='Installs dependencies listed within Gemfile.lock file of named repository'
 
@@ -19,7 +18,7 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_return_status="${1:-0}"
+	_message="${1}"
   _repo_name="${_repo_name:-repository-name}"
   cat <<EOF
 ## Usage
@@ -39,7 +38,9 @@ usage(){
 # -h	--help help
 #  Displays this message and exits
 EOF
-	return "${_return_status}"
+	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+		printf 'Error - %s\n' "${_message}" >&2
+	fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -49,11 +50,8 @@ _valid_args=('--help|-h|help:bool'
 argument_parser '_args' '_valid_args'
 _exit_status="$?"
 
-_git_path="${HOME}/git/${_repo_name}"
-_bundle_path="${HOME}/.bundle/install"
 
-
-if ((_help)) || ((_exit_status)) || [ -z "${_repo_name}" ]; then
+if ((_help)) || ((_exit_status)); then
 	usage "${_exit_status}"
 	exit "${_exit_status}"
 elif ((_license)); then
@@ -61,16 +59,24 @@ elif ((_license)); then
 	exit 0
 fi
 
+if [ -z "${_repo_name}" ]; then
+	usage 'missing repository name argument'
+	exit "1"
+fi
+
+_git_path="${HOME}/git/${_repo_name}"
+_bundle_path="${HOME}/.bundle/install"
 
 if ! [ -d "${_git_path}" ]; then
-  echo "# No repository ${_repo_name} at ${_git_path}"
+	printf '# No repository %s at %s\n' "${_repo_name}" "${_git_path}"
   exit 1
 fi
 
 if ! [ -d "${_git_path}/.git" ]; then
-  echo "# Repository ${_repo_name} maybe bare, this script cannot handle that right now"
+	printf '# Repository %s maybe bare, this script cannot handle that right now\n' "${_repo_name}"
   exit 1
 fi
+
 
 _pwd="${PWD}"
 cd "${_git_path}"
@@ -84,4 +90,4 @@ fi
 bundle install
 cd "${_pwd}"
 
-echo "# ${__NAME__} finished"
+printf '# %s finished\n' "${__NAME__}"
diff --git a/git_shell_commands/copy-theme b/git_shell_commands/copy-theme
--- a/git_shell_commands/copy-theme
+++ b/git_shell_commands/copy-theme
@@ -6,7 +6,6 @@ while [[ -h "${__SOURCE__}" ]]; do
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
-__PATH__="${__DIR__}/${__NAME__}"
 __AUTHOR__='S0AndS0'
 __DESCRIPTION__='Copies named theme files to named repository and git commits the changes'
 
@@ -22,7 +21,7 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_return_status="${1:-0}"
+	_message="${1}"
 	_repo_name="${_repo_name:-repository-name}"
 	_theme_name="${_theme_name:-theme-name}"
 	cat <<EOF
@@ -48,7 +47,9 @@ usage(){
 $(for _name in ${_available_theme_names[@]}; do printf '# %s\n' "${_name}"; done)
 #
 EOF
-	return "${_return_status}"
+	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+		printf 'Error - %s\n' "${_message}" >&2
+	fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -59,12 +60,17 @@ _valid_args=('--help|-h|help:bool'
 argument_parser '_args' '_valid_args'
 _exit_status="$?"
 
-if ((_help)) || ((_exit_status)) || [ -z "${_repo_name}" ]; then
+if ((_help)) || ((_exit_status)); then
 	usage "${_exit_status}"
-	exit "${_exit_status}"
+	exit "$?"
 elif ((_license)); then
 	__license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
 	exit 0
+fi
+
+if [ -z "${_repo_name}" ]; then
+	usage 'missing repository name argument!'
+	exit "1"
 fi
 
 
@@ -83,11 +89,6 @@ for _path in ${_gem_user_install_dir}/jekyll-theme-*; do
 	_available_theme_names+=("${_name}")
 done
 
-if ((_help)) || ((_exit_status)) || [ -z "${_repo_name}" ]; then
-	usage "${_exit_status}"
-	exit "$?"
-fi
-
 _git_path="${HOME}/git/${_repo_name}"
 _jekyll_config_yml_path="${_git_path}/_config.yml"
 _old_PWD="${PWD}"
@@ -102,7 +103,10 @@ if [[ "${_git_path}/${_git_dir}" != "${_git_path}/.git" ]] || ! [ -f "${_jekyll_
 	exit 1
 fi
 [[ -n "${_theme_name}" ]] || _theme_name="$(awk '/theme:/{print $2}' "${_jekyll_config_yml_path}")"
-if [ -z "${_theme_name}" ]; then usage; exit "$?"; fi
+if [ -z "${_theme_name}" ]; then
+	usage 'cannot find theme name!'
+	exit "1"
+fi
 
 for _theme_path in "${_available_theme_paths[@]}"; do
 	case "${_theme_path}" in
@@ -127,4 +131,4 @@ fi
 
 git_add_commit "Added files from ${_chosen_theme_name}"
 
-echo "# ${__NAME__} finished"
+printf '# %s finished\n' "${__NAME__}"
diff --git a/git_shell_commands/edit-configs b/git_shell_commands/edit-configs
--- a/git_shell_commands/edit-configs
+++ b/git_shell_commands/edit-configs
@@ -6,7 +6,6 @@ while [[ -h "${__SOURCE__}" ]]; do
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
-__PATH__="${__DIR__}/${__NAME__}"
 __AUTHOR__='S0AndS0'
 __DESCRIPTION__='Initializes Jekyll under gh-pages branch within named repository'
 
@@ -21,7 +20,7 @@ _config_dir="${HOME}/.config/jekyll-build"
 
 
 usage(){
-	_return_status="${1:-0}"
+	_message="${1}"
   _repo_name="${_repo_name:-repository-name}"
   cat <<EOF
 ## Usage
@@ -42,7 +41,9 @@ usage(){
 # -h	--help help
 #  Displays this message and exits
 EOF
-	return "${_return_status}"
+	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+		printf 'Error - %s\n' "${_message}" >&2
+	fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -65,6 +66,8 @@ if [ -n "${_github_api_token}" ]; then
 	${_github_api_token}
 	EOF
 else
-	usage "${_exit_status}"
-	exit "$?"
+	usage 'missing "--github-api-token" argument!'
+	exit "1"
 fi
+
+printf '%s finished!\n' "${__NAME__}"
diff --git a/git_shell_commands/git-init b/git_shell_commands/git-init
--- a/git_shell_commands/git-init
+++ b/git_shell_commands/git-init
@@ -1,11 +1,11 @@
 #!/usr/bin/env bash
+
 __SOURCE__="${BASH_SOURCE[0]}"
 while [[ -h "${__SOURCE__}" ]]; do
 	__SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
-__PATH__="${__DIR__}/${__NAME__}"
 __AUTHOR__='S0AndS0'
 __DESCRIPTION__='Initializes new git repository ready for cloning &/or pushing'
 
@@ -18,7 +18,7 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_return_status="${1:-0}"
+	_message="${1}"
 	_repo_name="${_repo_name:-repository-name}"
 	cat <<EOF
 ## Usage
@@ -55,7 +55,9 @@ usage(){
 # -h	--help help
 #  Display this message and exit
 EOF
-	return "${_return_status}"
+	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+		printf 'Error - %s\n' "${_message}" >&2
+	fi
 }
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
 _valid_args=('--help|-h|help:bool'
@@ -76,13 +78,19 @@ if ((_quiet)); then  _git_args+=('--quiet');  fi
 if [ -n "${_template}" ]; then  _git_args+=("--template='${_template}'"); fi
 if [ -n "${_repo_name}" ]; then _git_args+=("${_repo_name}"); fi
 
-if ((_help)) || ((_exit_status)) || [ -z "${_repo_name}" ]; then
+if ((_help)) || ((_exit_status)); then
 	usage "${_exit_status}"
 	exit "${_exit_status}"
 elif ((_license)); then
 	__license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
 	exit 0
 fi
+
+if [ -z "${_repo_name}" ]; then
+	usage 'missing repository name argument!'
+	exit "1"
+fi
+
 
 _git_path="${HOME}/git/${_repo_name:?# No repository name provided}"
 _git_parent_dir="${_git_path%/*}"
@@ -96,17 +104,17 @@ if [ -d "${_git_path}" ]; then
 	_git_preexisting_dir="$(git rev-parse --git-dir 2>/dev/null)"
 	if [[ "$?" == '0' ]] || [ -n "${_git_preexisting_dir}" ]; then
 		if [[ "${_git_preexisting_dir}" == "${_git_path}/.git" ]] || [[ "${_git_preexisting_dir}" == "${_git_path}" ]]; then
-			echo "# Already tracked by git: ${_git_preexisting_dir}"
+			printf '# Already tracked by git: %s\n' "${_git_preexisting_dir}"
 			exit 1
 		fi
 	fi
 fi
 
 cd "${_git_parent_dir}" || exit 1
-echo "## git init ${_git_args[@]}"
+printf '## git init %s\n' "${_git_args[@]}"
 git init ${_git_args[@]}
 
-if ! [[ "${_repo_bare}" ]]; then
+if ! ((_bare)); then
 	cd "${_git_parent_dir}/${_repo_name}" || exit 1
 	if [[ "$(git config receive.denyCurrentBranch)" != 'updateInstead' ]]; then
 		git config receive.denyCurrentBranch updateInstead
@@ -115,5 +123,5 @@ fi
 
 [[ "${_old_PWD}" == "${_git_path}" ]] || cd "${_old_PWD}"
 
-echo "# Clone ${_repo_name} via: git clone ${USER}@domain_or_ip:${_git_path//${HOME}\//}"
-echo "# ${__NAME__} finished"
+printf '# Clone %s via: git clone %s@domain_or_ip:%s\n' "${_repo_name}" "${USER}" "${_git_path//${HOME}\//}"
+printf '# %s finished\n' "${__NAME__}"
diff --git a/git_shell_commands/git-set-permissions b/git_shell_commands/git-set-permissions
--- a/git_shell_commands/git-set-permissions
+++ b/git_shell_commands/git-set-permissions
@@ -6,7 +6,6 @@ while [[ -h "${__SOURCE__}" ]]; do
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
-__PATH__="${__DIR__}/${__NAME__}"
 __AUTHOR__='S0AndS0'
 __DESCRIPTION__='Sets permissions for named repository to that of the $USER:$GROUP'
 
@@ -20,7 +19,7 @@ source "${__DIR__}/shared_functions/license"
 
 _group="$(groups | awk '{print $1}')"
 usage(){
-	_return_status="${1:-0}"
+	_message="${1}"
 	_repo_name="${_repo_name:-repository-name}"
 	cat <<EOF
 ## Usage
@@ -37,7 +36,9 @@ usage(){
 # -h	--help help
 #  Displays this message and exits
 EOF
-	return "${_return_status}"
+	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+		printf 'Error - %s\n' "${_message}" >&2
+	fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -49,7 +50,7 @@ _exit_status="$?"
 
 _git_path="${HOME}/git/${_repo_name}"
 
-if ((_help)) || ((_exit_status)) || [ -z "${_repo_name}" ]; then
+if ((_help)) || ((_exit_status)); then
 	usage "${_exit_status}"
 	exit "${_exit_status}"
 elif ((_license)); then
@@ -57,15 +58,20 @@ elif ((_license)); then
 	exit 0
 fi
 
+if [ -z "${_repo_name}" ]; then
+	usage 'missing repository name argument!'
+	exit "1"
+fi
 
 if ! [ -d "${_git_path}" ]; then
-	echo "# No repository ${_repo_name} at ${_git_path}"
+	printf '# No repository %s at %s\n' "${_repo_name}" "${_git_path}"
 	exit 1
 fi
+
 
 chown --recursive "${USER}":"${_group}" "${_git_path}"
 _prune_list='-path .git/hooks -o -path hooks -o path .git/objects/pack -o objects/pack'
 find "${_git_path}" -type d \( ${_prune_list} \) -prune -exec chmod 750 {} \;
 find "${_git_path}" -type f  \( ${_prune_list} \) -prune -exec chmod 640 {} \;
 
-echo "# ${__NAME__} finished"
+printf '# %s finished\n' "${__NAME__}"
diff --git a/git_shell_commands/jekyll-build b/git_shell_commands/jekyll-build
--- a/git_shell_commands/jekyll-build
+++ b/git_shell_commands/jekyll-build
@@ -6,7 +6,6 @@ while [[ -h "${__SOURCE__}" ]]; do
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
-__PATH__="${__DIR__}/${__NAME__}"
 __AUTHOR__='S0AndS0'
 __DESCRIPTION__='Initializes Jekyll under gh-pages branch within named repository'
 
@@ -19,13 +18,13 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_return_status="${1:-0}"
+	_message="${1}"
   _repo_name="${_repo_name:-repository-name}"
   cat <<EOF
 ## Usage
 # ssh ${USER}@host-or-ip ${__NAME__} ${_repo_name}
 #
-# $[__DESCRIPTION__]
+# ${__DESCRIPTION__}
 #
 # ${_repo_name}
 #  Name of repository to run
@@ -37,11 +36,15 @@ usage(){
 # -h	--help help
 #  Displays this message and exits
 EOF
-	return "${_return_status}"
+	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+		printf 'Error - %s\n' "${_message}" >&2
+	fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
-_valid_args=('--help|-h|help:bool' '--repo-name:posix-nil')
+_valid_args=('--help|-h|help:bool'
+             '--license|-l|license:bool'
+             '--repo-name:posix-nil')
 argument_parser '_args' '_valid_args'
 _exit_status="$?"
 
@@ -50,7 +53,7 @@ _www="${HOME}/www"
 _srv_path="${_www}/${_repo_name}"
 _github_api_token_path="${HOME}/.config/jekyll-build/github-api-token"
 
-if ((_help)) || ((_exit_status)) || [ -z "${_repo_name}" ]; then
+if ((_help)) || ((_exit_status)); then
 	usage "${_exit_status}"
 	exit "${_exit_status}"
 elif ((_license)); then
@@ -58,8 +61,17 @@ elif ((_license)); then
 	exit 0
 fi
 
+if [ -z "${_repo_name}" ]; then
+	usage 'missing repository name argument!'
+	exit "1"
+fi
 
-if ! [ -d "${_git_path}" ]; then echo "# No repository ${_repo_name} at ${_git_path}"; exit 1; fi
+if ! [ -d "${_git_path}" ]; then
+	printf '# No repository %s at %s\n' "${_repo_name}" "${_git_path}"
+	exit 1
+fi
+
+
 [[ -d "${_www}" ]] || mkdir -vp "${_www}"
 
 _pwd="${PWD}"
@@ -96,13 +108,13 @@ cd "${_pwd}"
 if [ -e "${HOME}/git-shell-commands/www-set-permissions" ]; then
   "${HOME}/git-shell-commands/www-set-permissions" "${_repo_name}"
 else
-  _current_group="$(groups ${USER} | awk '{print $3}')"
-  _www_group="$(groups ${USER} | grep -oE 'www[-a-z]{0,29}')"
+  _current_group="$(groups "${USER}" | awk '{print $3}')"
+  _www_group="$(groups "${USER}" | grep -oE 'www[-a-z]{0,29}')"
 	if [ -n "${_current_group}" ] && [ -n "${_www_group}" ]; then
-  	find "${_srv_path}" -group ${_current_group} -exec chgrp -h ${_www_group} {} \;
-	  find "${_srv_path}" -group ${_www_group} -type d -exec chmod 750 {} \;
-	  find "${_srv_path}" -group ${_www_group} -type f -exec chmod 640 {} \;
+  	find "${_srv_path}" -group "${_current_group}" -exec chgrp -h "${_www_group}" {} \;
+	  find "${_srv_path}" -group "${_www_group}" -type d -exec chmod 750 {} \;
+	  find "${_srv_path}" -group "${_www_group}" -type f -exec chmod 640 {} \;
 	fi
 fi
 
-echo "# ${__NAME__} finished"
+printf '# %s finished\n' "${__NAME__}"
diff --git a/git_shell_commands/jekyll-init b/git_shell_commands/jekyll-init
--- a/git_shell_commands/jekyll-init
+++ b/git_shell_commands/jekyll-init
@@ -6,7 +6,6 @@ while [[ -h "${__SOURCE__}" ]]; do
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
-__PATH__="${__DIR__}/${__NAME__}"
 __AUTHOR__='S0AndS0'
 __DESCRIPTION__='Initializes new Git repository with a gh-pages branch'
 
@@ -22,7 +21,7 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_return_status="${1:-0}"
+	_message="${1}"
 	_repo_name="${_repo_name:-repository-name}"
 	cat <<EOF
 ## Usage
@@ -63,7 +62,9 @@ usage(){
 # --twitter-username ${_twitter_username}
 # --github-username ${_github_username}
 EOF
-	return "${_return_status}"
+	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+		printf 'Error - %s\n' "${_message}" >&2
+	fi
 }
 
 
@@ -103,7 +104,7 @@ fi
 _bundle_path="${HOME}/.bundle/install"
 
 
-if ((_help)) || ((_exit_status)) || [ -z "${_repo_name}" ]; then
+if ((_help)) || ((_exit_status)); then
 	usage "${_exit_status}"
 	exit "${_exit_status}"
 elif ((_license)); then
@@ -111,6 +112,10 @@ elif ((_license)); then
 	exit 0
 fi
 
+if [ -z "${_repo_name}" ]; then
+	usage 'missing repository name argument!'
+	exit "1"
+fi
 
 _git_path="${HOME}/git/${_repo_name:?No repository name provided}"
 _old_PWD="${PWD}"
@@ -119,9 +124,9 @@ _git_dir="$(git rev-parse --git-dir 2>/dev/null)"
 
 
 if [[ "${_git_path}/${_git_dir}" == "${_git_path}/.git" ]]; then
-	printf '# Skipping git init, path already tracked by git: %s' "${_git_preexisting_dir}"
+	printf '# Skipping git init, path already tracked by git: %s\n' "${_git_preexisting_dir}"
 elif [[ "${_git_path}/${_git_dir}" == "${_git_path}/." ]]; then
-	printf '# Bare git repository detected, cannot install Jekyll to that right now'
+	echo '# Bare git repository detected, cannot install Jekyll to that right now'
 	exit 1
 else
 	if [ -e "${HOME}/git-shell-commands/git-init" ]; then
@@ -138,7 +143,7 @@ _git_branches="$(git branch --list)"
 _orig_branch="$(awk '/\*/{print $2}' <<<"${_git_branches}")"
 _pages_branch="$(awk '/gh-pages/{print $2}' <<<"${_git_branches}")"
 if [ -n "${_pages_branch}" ]; then
-	echo "# There is already a pages branch ${_pages_branch} for repository ${_repo_name}"
+	printf '# There is already a pages branch %s for repository %s\n' "${_pages_branch}" "${_repo_name}"
 	exit 1
 fi
 
@@ -157,13 +162,13 @@ if ((_clean)); then
 		esac
 		git rm -rf "${_path}"
 	done
-	git_add_commit "Cleaned gh-pages branch of files from parent branch"
+	git_add_commit 'Cleaned gh-pages branch of files from parent branch'
 fi
 
 
 modify_config_yml(){
 	if ! [ -f "${_git_path}/_config.yml" ]; then
-		printf 'Error - no Jekyll config file found under %s' "${_git_path}" >&2
+		printf 'Error - no Jekyll config file found under %s\n' "${_git_path}" >&2
 		return 1
 	fi
 
@@ -206,10 +211,10 @@ vendor
 Gemfile.lock
 EOF
 
-git_add_commit "Added files from Bundler & Jekyll to git tracking"
+git_add_commit 'Added files from Bundler & Jekyll to git tracking'
 
 [[ "${_old_PWD}" == "${_git_path}" ]] || cd "${_old_PWD}"
 
 
-echo "# Clone ${_repo_name} via: git clone ${USER}@domain_or_ip:${_git_path//${HOME}\//}"
-echo "# ${__NAME__} finished"
+printf '# Clone %s via: git clone %s@domain_or_ip:%s\n' "${_repo_name}" "${USER}" "${_git_path//${HOME}\//}"
+printf '# %s finished\n' "${__NAME__}"
diff --git a/git_shell_commands/list b/git_shell_commands/list
--- a/git_shell_commands/list
+++ b/git_shell_commands/list
@@ -6,7 +6,6 @@ while [[ -h "${__SOURCE__}" ]]; do
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
-__PATH__="${__DIR__}/${__NAME__}"
 __AUTHOR__='S0AndS0'
 __DESCRIPTION__='Runs "ls -hl" against supplied path within home directory'
 
@@ -19,7 +18,7 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_return_status="${1}"
+	_message="${1}"
 	_print_path="${_path//${HOME}\//}"
 	cat <<EOF
 ## Usage
@@ -34,8 +33,11 @@ usage(){
 #  Displays this message and exits
 #
 EOF
-	ls -hl "${_path}"
-	return "${_return_status:-$?}"
+	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+		printf 'Error - %s\n' "${_message}" >&2
+	else
+		ls -hl "${_path}"
+	fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -56,6 +58,11 @@ elif ((_license)); then
 	exit 0
 fi
 
+if [ -z "${_path}" ]; then
+	usage 'missing path argument!'
+	exit "1"
+fi
+
 
 if [ -d "${HOME}/${_path}" ]; then
 	ls -hl "${HOME}/${_path}"; exit $?
@@ -65,4 +72,4 @@ else
 	usage; exit 1
 fi
 
-echo "# ${__NAME__} finished"
+printf '# %s finished\n' "${__NAME__}"
diff --git a/git_shell_commands/www-remove b/git_shell_commands/www-remove
--- a/git_shell_commands/www-remove
+++ b/git_shell_commands/www-remove
@@ -6,7 +6,6 @@ while [[ -h "${__SOURCE__}" ]]; do
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
-__PATH__="${__DIR__}/${__NAME__}"
 __AUTHOR__='S0AndS0'
 __DESCRIPTION__='Removes site files &/or directories for named repository from "~/www" directory'
 
@@ -19,7 +18,7 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_return_status="${1:-0}"
+	_message="${1}"
 	_repo_name="${_repo_name:-repository-name}"
 	cat <<EOF
 ## Usage
@@ -38,7 +37,9 @@ usage(){
 # -h	--help help
 #  Displays this message and exits
 EOF
-	return "${_return_status}"
+	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+		printf 'Error - %s\n' "${_message}" >&2
+	fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -50,7 +51,7 @@ _exit_status="$?"
 
 _www_path="${HOME}/www/${_repo_name,,}"
 
-if ((_help)) || ((_exit_status)) || [ -z "${_repo_name}" ]; then
+if ((_help)) || ((_exit_status)); then
 	usage "${_exit_status}"
 	exit "$?"
 elif ((_license)); then
@@ -58,6 +59,12 @@ elif ((_license)); then
 	exit 0
 fi
 
+if [ -z "${_repo_name}" ]; then
+	usage 'missing repository name argument!'
+	exit "1"
+fi
+
+
 [[ -d "${_www_path}" ]] && rm -rfv "${_www_path}"
 
-echo "# ${__NAME__} finished"
+printf '# %s finished\n' "${__NAME__}"
diff --git a/git_shell_commands/www-set-permissions b/git_shell_commands/www-set-permissions
--- a/git_shell_commands/www-set-permissions
+++ b/git_shell_commands/www-set-permissions
@@ -6,7 +6,6 @@ while [[ -h "${__SOURCE__}" ]]; do
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
-__PATH__="${__DIR__}/${__NAME__}"
 __AUTHOR__='S0AndS0'
 __DESCRIPTION__='Sets permissions for named repository site files under "~/www" directory'
 
@@ -19,7 +18,7 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_return_status="${1:-0}"
+	_message="${1}"
 	_repo_name="${_repo_name:-repository-name}"
 	cat <<EOF
 ## Usage
@@ -37,7 +36,9 @@ usage(){
 # -h	--help help
 #  Displays this message and exits
 EOF
-	return "${_return_status}"
+	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+		printf 'Error - %s\n' "${_message}" >&2
+	fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -47,12 +48,7 @@ _valid_args=('--help|-h|help:bool'
 argument_parser '_args' '_valid_args'
 _exit_status="$?"
 
-_www="${HOME}/www"
-_www_group="$(groups ${USER} | grep -oE 'www[-a-z]{0,29}')"
-_srv_path="${_www}/${_repo_name,,}"
-
-
-if ((_help)) || ((_exit_status)) || [ -z "${_repo_name}" ]; then
+if ((_help)) || ((_exit_status)); then
 	usage "${_exit_status}"
 	exit "$?"
 elif ((_license)); then
@@ -60,15 +56,23 @@ elif ((_license)); then
 	exit 0
 fi
 
+if [ -z "${_repo_name}" ]; then
+	usage 'missing repository name argument!'
+	exit "1"
+fi
+
+_www="${HOME}/www"
+_www_group="$(groups ${USER} | grep -oE 'www[-a-z]{0,29}')"
+_srv_path="${_www}/${_repo_name,,}"
 
 if [ -z "${_www_group}" ]; then
-	echo "# No www group found for ${USER}"
+	printf '# No www group found for %s\n' "${USER}"
 	exit 1
 fi
 if ! [ -d "${_www}" ]; then
-	echo "# No www directory at ${_www}"
+	printf '# No www directory at %s\n' "${_www}"
 	if [ -e "${HOME}/git-shell-commands/jekyll-build"]; then
-		echo "# try: ssh ${USER}@host-or-ip jekyll-build ${_repo_name}"
+		printf '# try: ssh %s@host-or-ip jekyll-build %s\n' "${USER}" "${_repo_name}"
 	fi
 	exit 1
 fi
@@ -77,4 +81,4 @@ chown --recursive "${USER}":"${_www_group}" "${_srv_path}"
 find "${_srv_path}" -type d -exec chmod 750 {} \;
 find "${_srv_path}" -type f -exec chmod 640 {} \;
 
-echo "# ${__NAME__} finished"
+printf '# %s finished\n' "${__NAME__}"
