Converted tabs to spaces and added contributing file to .github dir

diff --git a/git_shell_commands/copy-theme b/git_shell_commands/copy-theme
--- a/git_shell_commands/copy-theme
+++ b/git_shell_commands/copy-theme
@@ -2,7 +2,7 @@
 
 __SOURCE__="${BASH_SOURCE[0]}"
 while [[ -h "${__SOURCE__}" ]]; do
-	__SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
+    __SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
@@ -21,16 +21,16 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_message="${1}"
-	_repo_name="${_repo_name:-repository-name}"
-	_theme_name="${_theme_name:-theme-name}"
-	cat <<EOF
+    _message="${1}"
+    _repo_name="${_repo_name:-repository-name}"
+    _theme_name="${_theme_name:-theme-name}"
+    cat <<EOF
 ## Usage
 # ssh ${USER}@host-or-ip ${__NAME__} ${_git_args[@]:-repository-name}
 #
 # ${__DESCRIPTION__}
 #
-# -t	--theme --theme-name=${_theme_name}
+# -t    --theme --theme-name=${_theme_name}
 #  Name of theme to copy to ${_repo_name} source directory
 #
 # ${_repo_name}
@@ -39,7 +39,7 @@ usage(){
 # -l --license
 # Shows script or project license then exits
 #
-# -h	--help help
+# -h    --help help
 #  Displays this message and exits
 #
 ## Available theme names
@@ -47,30 +47,30 @@ usage(){
 $(for _name in ${_available_theme_names[@]}; do printf '# %s\n' "${_name}"; done)
 #
 EOF
-	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-		printf 'Error - %s\n' "${_message}" >&2
-	fi
+    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+        printf 'Error - %s\n' "${_message}" >&2
+    fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
 _valid_args=('--help|-h|help:bool'
              '--license|-l|license:bool'
              '--theme-name|--theme|-t:posix'
-						 '--repo-name:posix-nil')
+             '--repo-name:posix-nil')
 argument_parser '_args' '_valid_args'
 _exit_status="$?"
 
 if ((_help)) || ((_exit_status)); then
-	usage "${_exit_status}"
-	exit "$?"
+    usage "${_exit_status}"
+    exit "$?"
 elif ((_license)); then
-	__license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
-	exit 0
+    __license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
+    exit 0
 fi
 
 if [ -z "${_repo_name}" ]; then
-	usage 'missing repository name argument!'
-	exit "1"
+    usage 'missing repository name argument!'
+    exit "1"
 fi
 
 
@@ -81,12 +81,12 @@ _gem_user_install_dir="${HOME}/.bundle/install/ruby/${_gem_user_version}/gems"
 _available_theme_paths=()
 _available_theme_names=()
 for _path in ${_gem_user_install_dir}/jekyll-theme-*; do
-	## Strip file path and 'jekyll-theme-' header
-	_name="${_path##*/jekyll-theme-}"
-	## Strip version from end
-	_name="${_name%-*}"
-	_available_theme_paths+=("${_path}")
-	_available_theme_names+=("${_name}")
+    ## Strip file path and 'jekyll-theme-' header
+    _name="${_path##*/jekyll-theme-}"
+    ## Strip version from end
+    _name="${_name%-*}"
+    _available_theme_paths+=("${_path}")
+    _available_theme_names+=("${_name}")
 done
 
 _git_path="${HOME}/git/${_repo_name}"
@@ -96,37 +96,37 @@ if [ -d "${_git_path}" ]; then cd "${_git_path}"; fi
 
 _git_dir="$(git rev-parse --git-dir 2>/dev/null)"
 if [[ "${_git_path}/${_git_dir}" != "${_git_path}/.git" ]] || ! [ -f "${_jekyll_config_yml_path}" ]; then
-	printf '# Repository %s not initialized correctly\n' "${_repo_name}"
-	if [ -e "${HOME}/git-shell-commands/jekyll-init" ]; then
-		printf '# Try: ssh ${USER}@host-or-ip jekyll-init %s\n' "${_repo_name}"
-	fi
-	exit 1
+    printf '# Repository %s not initialized correctly\n' "${_repo_name}"
+    if [ -e "${HOME}/git-shell-commands/jekyll-init" ]; then
+        printf '# Try: ssh ${USER}@host-or-ip jekyll-init %s\n' "${_repo_name}"
+    fi
+    exit 1
 fi
 [[ -n "${_theme_name}" ]] || _theme_name="$(awk '/theme:/{print $2}' "${_jekyll_config_yml_path}")"
 if [ -z "${_theme_name}" ]; then
-	usage 'cannot find theme name!'
-	exit "1"
+    usage 'cannot find theme name!'
+    exit "1"
 fi
 
 for _theme_path in "${_available_theme_paths[@]}"; do
-	case "${_theme_path}" in
-		*"/jekyll-theme-${_theme_name}"*)
-			_chosen_theme_path="${_theme_path}"
-			_chosen_theme_name="${_chosen_theme_path##*/jekyll-theme-}"
-			_chosen_theme_name="${_chosen_theme_name%-*}"
-			break
-		;;
-	esac
+    case "${_theme_path}" in
+        *"/jekyll-theme-${_theme_name}"*)
+            _chosen_theme_path="${_theme_path}"
+            _chosen_theme_name="${_chosen_theme_path##*/jekyll-theme-}"
+            _chosen_theme_name="${_chosen_theme_name%-*}"
+            break
+        ;;
+    esac
 done
 if [ -z "${_chosen_theme_name}" ] || ! [ -d "${_chosen_theme_path}" ]; then usage; exit "$?"; fi
 
 for _path in $(ls -1 "${_chosen_theme_path}"); do
-	if ! [ -d "${_chosen_theme_path}/${_path}" ]; then continue; fi
-	rsync -av --progress "${_chosen_theme_path}/${_path}" "${_git_path}/" --exclude "assets/fonts"
-	# cp -vr "${_chosen_theme_path}/${_path}" "${_git_path}/"
+    if ! [ -d "${_chosen_theme_path}/${_path}" ]; then continue; fi
+    rsync -av --progress "${_chosen_theme_path}/${_path}" "${_git_path}/" --exclude "assets/fonts"
+    # cp -vr "${_chosen_theme_path}/${_path}" "${_git_path}/"
 done
 if [ -f "${_chosen_theme_path}/LICENSE" ]; then
-	cp -v "${_chosen_theme_path}/LICENSE" "${_git_path}/LICENSE_${_chosen_theme_name}"
+    cp -v "${_chosen_theme_path}/LICENSE" "${_git_path}/LICENSE_${_chosen_theme_name}"
 fi
 
 git_add_commit "Added files from ${_chosen_theme_name}"
diff --git a/git_shell_commands/edit-configs b/git_shell_commands/edit-configs
--- a/git_shell_commands/edit-configs
+++ b/git_shell_commands/edit-configs
@@ -2,7 +2,7 @@
 
 __SOURCE__="${BASH_SOURCE[0]}"
 while [[ -h "${__SOURCE__}" ]]; do
-	__SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
+    __SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
@@ -20,7 +20,7 @@ _config_dir="${HOME}/.config/jekyll-build"
 
 
 usage(){
-	_message="${1}"
+    _message="${1}"
   _repo_name="${_repo_name:-repository-name}"
   cat <<EOF
 ## Usage
@@ -38,12 +38,12 @@ usage(){
 # -l --license
 # Shows script or project license then exits
 #
-# -h	--help help
+# -h    --help help
 #  Displays this message and exits
 EOF
-	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-		printf 'Error - %s\n' "${_message}" >&2
-	fi
+    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+        printf 'Error - %s\n' "${_message}" >&2
+    fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -52,22 +52,22 @@ argument_parser '_args' '_valid_args'
 _exit_status="$?"
 
 if ((_help)) || ((_exit_status)); then
-	usage "${_exit_status}"
-	exit "${_exit_status}"
+    usage "${_exit_status}"
+    exit "${_exit_status}"
 elif ((_license)); then
-	__license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
-	exit 0
+    __license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
+    exit 0
 fi
 
 
 if [ -n "${_github_api_token}" ]; then
-	mkdir -vp "${_config_dir}"
-	tee "${_config_dir}/github-api-token" 1>/dev/null <<-EOF
-	${_github_api_token}
-	EOF
+    mkdir -vp "${_config_dir}"
+    tee "${_config_dir}/github-api-token" 1>/dev/null <<-EOF
+    ${_github_api_token}
+    EOF
 else
-	usage 'missing "--github-api-token" argument!'
-	exit "1"
+    usage 'missing "--github-api-token" argument!'
+    exit "1"
 fi
 
 printf '%s finished!\n' "${__NAME__}"
diff --git a/git_shell_commands/git-checkout b/git_shell_commands/git-checkout
--- a/git_shell_commands/git-checkout
+++ b/git_shell_commands/git-checkout
@@ -2,7 +2,7 @@
 
 __SOURCE__="${BASH_SOURCE[0]}"
 while [[ -h "${__SOURCE__}" ]]; do
-	__SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
+    __SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
@@ -18,11 +18,11 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_message="${1}"
-	_repo_name="${_repo_name:-repository-name}"
-	_branch="${_branch:-new-branch-name}"
-	_branch_name="${_branch_name:-existing-branch-name}"
-	cat <<EOF
+    _message="${1}"
+    _repo_name="${_repo_name:-repository-name}"
+    _branch="${_branch:-new-branch-name}"
+    _branch_name="${_branch_name:-existing-branch-name}"
+    cat <<EOF
 ## Usage
 # ssh ${USER}@host-or-ip ${__NAME__} ${_git_args[@]:-$_repo_name}
 #
@@ -40,12 +40,12 @@ usage(){
 # -l --license
 # Shows script or project license then exits
 #
-# -h	--help help
+# -h    --help help
 #  Display this message and exit
 EOF
-	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-		printf 'Error - %s\n' "${_message}" >&2
-	fi
+    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+        printf 'Error - %s\n' "${_message}" >&2
+    fi
 }
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
 _valid_args=('--help|-h|help:bool'
@@ -58,47 +58,47 @@ _exit_status="$?"
 
 ## Catch --branch <name> <repo>
 if [ -n "${_branch}" ]; then
-	_repo_name="${_branch_name}"
-	_branch_name=''
+    _repo_name="${_branch_name}"
+    _branch_name=''
 fi
 
 if ((_help)) || ((_exit_status)); then
-	usage "${_exit_status}"
-	exit "${_exit_status}"
+    usage "${_exit_status}"
+    exit "${_exit_status}"
 elif ((_license)); then
-	__license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
-	exit 0
+    __license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
+    exit 0
 fi
 
 if [ -z "${_repo_name}" ]; then
-	usage 'missing repository name argument!'
-	exit "1"
+    usage 'missing repository name argument!'
+    exit "1"
 fi
 
 if [ -z "${_branch}" ] && [ -z "${_branch_name}" ]; then
-	usage 'missing "--branch" or "--branch-name" argument!'
-	exit "1"
+    usage 'missing "--branch" or "--branch-name" argument!'
+    exit "1"
 fi
 
 
 _git_path="${HOME}/git/${_repo_name:?# No repository name provided}"
 if ! [ -d "${_git_path}" ]; then
-	usage "no repository found with ${_repo_name}"
-	exit "1"
+    usage "no repository found with ${_repo_name}"
+    exit "1"
 elif ! [ -d "${_git_path}/.git" ]; then
-	usage "directory found with ${_repo_name} but not initialized correctly"
-	exit "1"
+    usage "directory found with ${_repo_name} but not initialized correctly"
+    exit "1"
 fi
 
 
 _git_args=()
 if [ -n "${_branch}" ]; then
-	_git_args+=('-b' "${_branch}")
+    _git_args+=('-b' "${_branch}")
 elif [ -n "${_branch_name}" ]; then
-	_git_args+=("${_branch}")
+    _git_args+=("${_branch}")
 else
-	usage 'missing "--branch" or "--branch-name" argument!'
-	exit 1
+    usage 'missing "--branch" or "--branch-name" argument!'
+    exit 1
 fi
 
 _old_PWD="${PWD}"
@@ -108,8 +108,8 @@ _git_exit_status="${?}"
 [[ "${_old_PWD}" == "${_git_path}" ]] || cd "${_old_PWD}"
 
 if ((_git_exit_status)); then
-	printf '%s encountered errors!\n' "${__NAME__}"
-	exit 1
+    printf '%s encountered errors!\n' "${__NAME__}"
+    exit 1
 fi
 
 printf '%s finished!\n' "${__NAME__}"
diff --git a/git_shell_commands/git-init b/git_shell_commands/git-init
--- a/git_shell_commands/git-init
+++ b/git_shell_commands/git-init
@@ -2,7 +2,7 @@
 
 __SOURCE__="${BASH_SOURCE[0]}"
 while [[ -h "${__SOURCE__}" ]]; do
-	__SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
+    __SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
@@ -18,9 +18,9 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_message="${1}"
-	_repo_name="${_repo_name:-repository-name}"
-	cat <<EOF
+    _message="${1}"
+    _repo_name="${_repo_name:-repository-name}"
+    cat <<EOF
 ## Usage
 # ssh ${USER}@host-or-ip ${__NAME__} ${_git_args[@]:-$_repo_name}
 #
@@ -52,21 +52,21 @@ usage(){
 # -l --license
 # Shows script or project license then exits
 #
-# -h	--help help
+# -h    --help help
 #  Display this message and exit
 EOF
-	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-		printf 'Error - %s\n' "${_message}" >&2
-	fi
+    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+        printf 'Error - %s\n' "${_message}" >&2
+    fi
 }
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
 _valid_args=('--help|-h|help:bool'
-						 '--quiet:bool'
-						 '--license|-l|license:bool'
-						 '--bare:bool'
-						 '--shared:bool'
-						 '--template:path'
-						 '--repo-name:posix-nil')
+             '--quiet:bool'
+             '--license|-l|license:bool'
+             '--bare:bool'
+             '--shared:bool'
+             '--template:path'
+             '--repo-name:posix-nil')
 argument_parser '_args' '_valid_args'
 _exit_status="$?"
 
@@ -79,16 +79,16 @@ if [ -n "${_template}" ]; then  _git_args+=("--template='${_template}'"); fi
 if [ -n "${_repo_name}" ]; then _git_args+=("${_repo_name}"); fi
 
 if ((_help)) || ((_exit_status)); then
-	usage "${_exit_status}"
-	exit "${_exit_status}"
+    usage "${_exit_status}"
+    exit "${_exit_status}"
 elif ((_license)); then
-	__license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
-	exit 0
+    __license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
+    exit 0
 fi
 
 if [ -z "${_repo_name}" ]; then
-	usage 'missing repository name argument!'
-	exit "1"
+    usage 'missing repository name argument!'
+    exit "1"
 fi
 
 
@@ -100,14 +100,14 @@ _old_PWD="${PWD}"
 [[ -d "${_git_parent_dir}" ]] || mkdir -vp "${_git_parent_dir}"
 ## Check if path is already tracked by git
 if [ -d "${_git_path}" ]; then
-	cd "${_git_path}" || exit 1
-	_git_preexisting_dir="$(git rev-parse --git-dir 2>/dev/null)"
-	if [[ "$?" == '0' ]] || [ -n "${_git_preexisting_dir}" ]; then
-		if [[ "${_git_preexisting_dir}" == "${_git_path}/.git" ]] || [[ "${_git_preexisting_dir}" == "${_git_path}" ]]; then
-			printf '# Already tracked by git: %s\n' "${_git_preexisting_dir}"
-			exit 1
-		fi
-	fi
+    cd "${_git_path}" || exit 1
+    _git_preexisting_dir="$(git rev-parse --git-dir 2>/dev/null)"
+    if [[ "$?" == '0' ]] || [ -n "${_git_preexisting_dir}" ]; then
+        if [[ "${_git_preexisting_dir}" == "${_git_path}/.git" ]] || [[ "${_git_preexisting_dir}" == "${_git_path}" ]]; then
+            printf '# Already tracked by git: %s\n' "${_git_preexisting_dir}"
+            exit 1
+        fi
+    fi
 fi
 
 cd "${_git_parent_dir}" || exit 1
@@ -116,10 +116,10 @@ git init ${_git_args[@]}
 
 ## Allow 'git push' on non-bare repositories
 if ! ((_bare)); then
-	cd "${_git_parent_dir}/${_repo_name}" || exit 1
-	if [[ "$(git config receive.denyCurrentBranch)" != 'updateInstead' ]]; then
-		git config receive.denyCurrentBranch updateInstead
-	fi
+    cd "${_git_parent_dir}/${_repo_name}" || exit 1
+    if [[ "$(git config receive.denyCurrentBranch)" != 'updateInstead' ]]; then
+        git config receive.denyCurrentBranch updateInstead
+    fi
 fi
 
 [[ "${_old_PWD}" == "${_git_path}" ]] || cd "${_old_PWD}"
diff --git a/git_shell_commands/jekyll-build b/git_shell_commands/jekyll-build
--- a/git_shell_commands/jekyll-build
+++ b/git_shell_commands/jekyll-build
@@ -2,7 +2,7 @@
 
 __SOURCE__="${BASH_SOURCE[0]}"
 while [[ -h "${__SOURCE__}" ]]; do
-	__SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
+    __SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
@@ -18,7 +18,7 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_message="${1}"
+    _message="${1}"
   _repo_name="${_repo_name:-repository-name}"
   cat <<EOF
 ## Usage
@@ -33,12 +33,12 @@ usage(){
 # -l --license
 # Shows script or project license then exits
 #
-# -h	--help help
+# -h    --help help
 #  Displays this message and exits
 EOF
-	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-		printf 'Error - %s\n' "${_message}" >&2
-	fi
+    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+        printf 'Error - %s\n' "${_message}" >&2
+    fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -54,39 +54,39 @@ _srv_path="${_www}/${_repo_name}"
 _github_api_token_path="${HOME}/.config/jekyll-build/github-api-token"
 
 if ((_help)) || ((_exit_status)); then
-	usage "${_exit_status}"
-	exit "${_exit_status}"
+    usage "${_exit_status}"
+    exit "${_exit_status}"
 elif ((_license)); then
-	__license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
-	exit 0
+    __license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
+    exit 0
 fi
 
 if [ -z "${_repo_name}" ]; then
-	usage 'missing repository name argument!'
-	exit "1"
+    usage 'missing repository name argument!'
+    exit "1"
 fi
 
 if ! [ -d "${_git_path}" ]; then
-	printf '# No repository %s at %s\n' "${_repo_name}" "${_git_path}"
-	exit 1
+    printf '# No repository %s at %s\n' "${_repo_name}" "${_git_path}"
+    exit 1
 fi
 
 
 if [ -f "${_git_path}/_config.yml" ]; then
-	_config_files="_config.yml"
+    _config_files="_config.yml"
 elif [ -f "${_git_path}/_config.yaml" ]; then
-	_config_files="_config.yaml"
+    _config_files="_config.yaml"
 else
-	printf '%s has no _config.yml or _config.yaml file\n' "${_repo_name}"
-	exit 1
+    printf '%s has no _config.yml or _config.yaml file\n' "${_repo_name}"
+    exit 1
 fi
 
 ## Build cama seperated list of _config*.yml files
 while read _p; do
-	_f="${_p##*/}"
-	if [[ "${_f}" != '_config.yml' ]] || [[ "${_f}" != '_config.yaml' ]]; then
-		_config_files+=",${_f}"
-	fi
+    _f="${_p##*/}"
+    if [[ "${_f}" != '_config.yml' ]] || [[ "${_f}" != '_config.yaml' ]]; then
+        _config_files+=",${_f}"
+    fi
 done < <(ls -1 "${_git_path}"/_config*.y*ml)
 
 
@@ -98,11 +98,11 @@ source "${HOME}/.bash_aliases"
 
 ## Use API keys if configured for repo and available to user during build process
 if grep -q -- 'jekyll-github-metadata' "${_git_path}/Gemfile" && [ -f "${_github_api_token_path}" ]; then
-	printf '# JEKYLL_GITHUB_TOKEN="$(<github-api-token-path)" bundle exec jekyll build --destination %s --config %s\n' "${_srv_path}" "${_config_files}"
-	JEKYLL_GITHUB_TOKEN="$(<"${_github_api_token_path}")" bundle exec jekyll build --destination "${_srv_path}" --config "${_config_files}"
+    printf '# JEKYLL_GITHUB_TOKEN="$(<github-api-token-path)" bundle exec jekyll build --destination %s --config %s\n' "${_srv_path}" "${_config_files}"
+    JEKYLL_GITHUB_TOKEN="$(<"${_github_api_token_path}")" bundle exec jekyll build --destination "${_srv_path}" --config "${_config_files}"
 else
-	printf '# bundle exec jekyll build --destination "%s" --config "%s"\n' "${_srv_path}" "${_config_files}"
-	bundle exec jekyll build --destination "${_srv_path}" --config "${_config_files}"
+    printf '# bundle exec jekyll build --destination "%s" --config "%s"\n' "${_srv_path}" "${_config_files}"
+    bundle exec jekyll build --destination "${_srv_path}" --config "${_config_files}"
 fi
 
 [[ "${_pwd}" == "${_git_path}" ]] || cd "${_pwd}"
@@ -113,11 +113,11 @@ if [ -e "${HOME}/git-shell-commands/www-set-permissions" ]; then
 else
   _current_group="$(groups "${USER}" | awk '{print $3}')"
   _www_group="$(groups "${USER}" | grep -oE 'www[-a-z]{0,29}')"
-	if [ -n "${_current_group}" ] && [ -n "${_www_group}" ]; then
-  	find "${_srv_path}" -group "${_current_group}" -exec chgrp -h "${_www_group}" {} \;
-	  find "${_srv_path}" -group "${_www_group}" -type d -exec chmod 750 {} \;
-	  find "${_srv_path}" -group "${_www_group}" -type f -exec chmod 640 {} \;
-	fi
+    if [ -n "${_current_group}" ] && [ -n "${_www_group}" ]; then
+      find "${_srv_path}" -group "${_current_group}" -exec chgrp -h "${_www_group}" {} \;
+      find "${_srv_path}" -group "${_www_group}" -type d -exec chmod 750 {} \;
+      find "${_srv_path}" -group "${_www_group}" -type f -exec chmod 640 {} \;
+    fi
 fi
 
 printf '# %s finished\n' "${__NAME__}"
diff --git a/git_shell_commands/jekyll-init b/git_shell_commands/jekyll-init
--- a/git_shell_commands/jekyll-init
+++ b/git_shell_commands/jekyll-init
@@ -2,7 +2,7 @@
 
 __SOURCE__="${BASH_SOURCE[0]}"
 while [[ -h "${__SOURCE__}" ]]; do
-	__SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
+    __SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
@@ -21,9 +21,9 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_message="${1}"
-	_repo_name="${_repo_name:-repository-name}"
-	cat <<EOF
+    _message="${1}"
+    _repo_name="${_repo_name:-repository-name}"
+    cat <<EOF
 ## Usage
 # ssh ${USER}@host-or-ip ${__NAME__} ${_git_args[@]:-$_repo_name}
 #
@@ -52,7 +52,7 @@ usage(){
 # -l --license
 # Shows script or project license then exits
 #
-# -h	--help help
+# -h    --help help
 #  Displays this message and exits
 #
 ## The following options maybe used to modify the generated _config.yml file
@@ -62,24 +62,24 @@ usage(){
 # --twitter-username ${_twitter_username}
 # --github-username ${_github_username}
 EOF
-	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-		printf 'Error - %s\n' "${_message}" >&2
-	fi
+    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+        printf 'Error - %s\n' "${_message}" >&2
+    fi
 }
 
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
 _valid_args=('--help|-h|help:bool'
-						 '--license|-l|license:bool'
-						 '--quiet:bool'
-						 '--clean:bool'
-						 '--shared:bool'
-						 '--template:path'
-						 '--title:print'
-						 '--email:print'
-						 '--twitter-username:posix'
-						 '--github-username:posix'
-						 '--repo-name:posix-nil')
+             '--license|-l|license:bool'
+             '--quiet:bool'
+             '--clean:bool'
+             '--shared:bool'
+             '--template:path'
+             '--title:print'
+             '--email:print'
+             '--twitter-username:posix'
+             '--github-username:posix'
+             '--repo-name:posix-nil')
 argument_parser '_args' '_valid_args'
 _exit_status="$?"
 _git_args=()
@@ -92,29 +92,29 @@ if [ -n "${_repo_name}" ]; then _git_args+=("${_repo_name}"); fi
 ## Set defaults for some variables if not already set
 _github_username="${_github_username:-$USER}"
 if [ -z "${_title}" ]; then
-	for _word in ${_repo_name//[-_]/ }; do
-		if [[ "${#_word}" -ge '4' ]]; then
-			_temp_title+=("${_word^}")
-		else
-			_temp_title+=("${_word}")
-		fi
-	done
-	_title="${_temp_title[@]}"
+    for _word in ${_repo_name//[-_]/ }; do
+        if [[ "${#_word}" -ge '4' ]]; then
+            _temp_title+=("${_word^}")
+        else
+            _temp_title+=("${_word}")
+        fi
+    done
+    _title="${_temp_title[@]}"
 fi
 _bundle_path="${HOME}/.bundle/install"
 
 
 if ((_help)) || ((_exit_status)); then
-	usage "${_exit_status}"
-	exit "${_exit_status}"
+    usage "${_exit_status}"
+    exit "${_exit_status}"
 elif ((_license)); then
-	__license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
-	exit 0
+    __license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
+    exit 0
 fi
 
 if [ -z "${_repo_name}" ]; then
-	usage 'missing repository name argument!'
-	exit "1"
+    usage 'missing repository name argument!'
+    exit "1"
 fi
 
 _git_path="${HOME}/git/${_repo_name:?No repository name provided}"
@@ -124,17 +124,17 @@ _git_dir="$(git rev-parse --git-dir 2>/dev/null)"
 
 
 if [[ "${_git_path}/${_git_dir}" == "${_git_path}/.git" ]]; then
-	printf '# Skipping git init, path already tracked by git: %s\n' "${_git_preexisting_dir}"
+    printf '# Skipping git init, path already tracked by git: %s\n' "${_git_preexisting_dir}"
 elif [[ "${_git_path}/${_git_dir}" == "${_git_path}/." ]]; then
-	echo '# Bare git repository detected, cannot install Jekyll to that right now'
-	exit 1
+    echo '# Bare git repository detected, cannot install Jekyll to that right now'
+    exit 1
 else
-	if [ -e "${HOME}/git-shell-commands/git-init" ]; then
-		"${HOME}/git-shell-commands/git-init" ${_git_args[@]}
-	else
-		cd "${HOME}/git" || exit 1
-		git init ${_git_args[@]}
-	fi
+    if [ -e "${HOME}/git-shell-commands/git-init" ]; then
+        "${HOME}/git-shell-commands/git-init" ${_git_args[@]}
+    else
+        cd "${HOME}/git" || exit 1
+        git init ${_git_args[@]}
+    fi
 fi
 
 
@@ -143,54 +143,54 @@ _git_branches="$(git branch --list)"
 _orig_branch="$(awk '/\*/{print $2}' <<<"${_git_branches}")"
 _pages_branch="$(awk '/gh-pages/{print $2}' <<<"${_git_branches}")"
 if [ -n "${_pages_branch}" ]; then
-	printf '# There is already a pages branch %s for repository %s\n' "${_pages_branch}" "${_repo_name}"
-	exit 1
+    printf '# There is already a pages branch %s for repository %s\n' "${_pages_branch}" "${_repo_name}"
+    exit 1
 fi
 
 git_add_commit "Added files on ${_orig_branch} prior to installing Bundler & Jekyll to gh-pages branch"
 
 git checkout -b gh-pages
 if [[ "$(git config receive.denyCurrentBranch)" != 'updateInstead' ]]; then
-	git config receive.denyCurrentBranch updateInstead
+    git config receive.denyCurrentBranch updateInstead
 fi
 
 if ((_clean)); then
-	for _path in ${_git_path}/*; do
-		case "${_path}" in
-			*'.git')       [[ -d "${_path}" ]] && continue ;;
-			*'.gitignore') [[ -f "${_path}" ]] && continue ;;
-		esac
-		git rm -rf "${_path}"
-	done
-	git_add_commit 'Cleaned gh-pages branch of files from parent branch'
+    for _path in ${_git_path}/*; do
+        case "${_path}" in
+            *'.git')       [[ -d "${_path}" ]] && continue ;;
+            *'.gitignore') [[ -f "${_path}" ]] && continue ;;
+        esac
+        git rm -rf "${_path}"
+    done
+    git_add_commit 'Cleaned gh-pages branch of files from parent branch'
 fi
 
 
 modify_config_yml(){
-	if ! [ -f "${_git_path}/_config.yml" ]; then
-		printf 'Error - no Jekyll config file found under %s\n' "${_git_path}" >&2
-		return 1
-	fi
+    if ! [ -f "${_git_path}/_config.yml" ]; then
+        printf 'Error - no Jekyll config file found under %s\n' "${_git_path}" >&2
+        return 1
+    fi
 
-	if [ -n "${_title}" ]; then
-		sed -i "/title:/ { s#:[a-zA-Z 0-9]*#${_title}#; }" "${_git_path}/_config.yml"
-	fi
-	if [ -n "${_email}" ]; then
-		sed -i "/email:/ { s#:[a-zA-Z 0-9]*#${_email}#; }" "${_git_path}/_config.yml"
-	fi
-	if [ -n "${_twitter_username}" ]; then
-		sed -i "/_twitter_username:/ { s#:[a-zA-Z 0-9]*#${_twitter_username}#; }" "${_git_path}/_config.yml"
-	fi
-	if [ -n "${_github_username}" ]; then
-		sed -i "/github_username:/ { s#:[a-zA-Z 0-9]*#${_github_username}#; }" "${_git_path}/_config.yml"
-	fi
+    if [ -n "${_title}" ]; then
+        sed -i "/title:/ { s#:[a-zA-Z 0-9]*#${_title}#; }" "${_git_path}/_config.yml"
+    fi
+    if [ -n "${_email}" ]; then
+        sed -i "/email:/ { s#:[a-zA-Z 0-9]*#${_email}#; }" "${_git_path}/_config.yml"
+    fi
+    if [ -n "${_twitter_username}" ]; then
+        sed -i "/_twitter_username:/ { s#:[a-zA-Z 0-9]*#${_twitter_username}#; }" "${_git_path}/_config.yml"
+    fi
+    if [ -n "${_github_username}" ]; then
+        sed -i "/github_username:/ { s#:[a-zA-Z 0-9]*#${_github_username}#; }" "${_git_path}/_config.yml"
+    fi
 
-	if [[ "${_repo_name}" != "${_github_username}" ]]; then
-		tee -a "${_git_path}/_config_baseurl.yml" >/dev/null <<-EOF
-		# Use base URL to simulate GitHub pages behaviour
-		baseurl: "${_repo_name}"
-		EOF
-	fi
+    if [[ "${_repo_name}" != "${_github_username}" ]]; then
+        tee -a "${_git_path}/_config_baseurl.yml" >/dev/null <<-EOF
+        # Use base URL to simulate GitHub pages behaviour
+        baseurl: "${_repo_name}"
+        EOF
+    fi
 }
 
 
diff --git a/git_shell_commands/list b/git_shell_commands/list
--- a/git_shell_commands/list
+++ b/git_shell_commands/list
@@ -2,7 +2,7 @@
 
 __SOURCE__="${BASH_SOURCE[0]}"
 while [[ -h "${__SOURCE__}" ]]; do
-	__SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
+    __SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
@@ -18,10 +18,10 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_message="${1}"
-	_path="${_path:-${HOME}/git-shell-commands}"
-	_print_path="${_path//${HOME}\//}"
-	cat <<EOF
+    _message="${1}"
+    _path="${_path:-${HOME}/git-shell-commands}"
+    _print_path="${_path//${HOME}\//}"
+    cat <<EOF
 ## Usage
 # ssh ${USER}@host-or-ip ${__NAME__} ${_print_path}
 #
@@ -30,16 +30,16 @@ usage(){
 # -l --license
 # Shows script or project license then exits
 #
-# -h	--help help
+# -h    --help help
 #  Displays this message and exits
 #
 EOF
-	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-		printf 'Error - %s\n' "${_message}" >&2
-	else
-		echo '# Example of: list git-shell-commands'
-		ls -hl "${HOME}/git-shell-commands"
-	fi
+    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+        printf 'Error - %s\n' "${_message}" >&2
+    else
+        echo '# Example of: list git-shell-commands'
+        ls -hl "${HOME}/git-shell-commands"
+    fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -51,25 +51,25 @@ _exit_status="${?}"
 
 
 if ((_help)) || ((_exit_status)); then
-	usage "${_exit_status}"
-	exit "${_exit_status}"
+    usage "${_exit_status}"
+    exit "${_exit_status}"
 elif ((_license)); then
-	__license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
-	exit 0
+    __license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
+    exit 0
 fi
 
 if [ -z "${_path}" ]; then
-	usage 'missing path argument!'
-	exit "1"
+    usage 'missing path argument!'
+    exit "1"
 fi
 
 
 if [ -d "${HOME}/${_path}" ]; then
-	ls -hl "${HOME}/${_path}"; exit $?
+    ls -hl "${HOME}/${_path}"; exit $?
 elif [ -f "${HOME}/${_path}" ]; then
-	ls -hl "${HOME}/${_path}"; exit $?
+    ls -hl "${HOME}/${_path}"; exit $?
 else
-	usage; exit 1
+    usage; exit 1
 fi
 
 printf '# %s finished\n' "${__NAME__}"
diff --git a/git_shell_commands/repo-remove b/git_shell_commands/repo-remove
--- a/git_shell_commands/repo-remove
+++ b/git_shell_commands/repo-remove
@@ -2,7 +2,7 @@
 
 __SOURCE__="${BASH_SOURCE[0]}"
 while [[ -h "${__SOURCE__}" ]]; do
-	__SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
+    __SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
@@ -18,9 +18,9 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_message="${1}"
-	_repo_name="${_repo_name:-repository-name}"
-	cat <<EOF
+    _message="${1}"
+    _repo_name="${_repo_name:-repository-name}"
+    cat <<EOF
 ## Usage
 # ssh ${USER}@host-or-ip ${__NAME__} ${_repo_name}
 #
@@ -33,12 +33,12 @@ usage(){
 # -l --license
 # Shows script or project license then exits
 #
-# -h	--help help
+# -h    --help help
 #  Displays this message and exits
 EOF
-	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-		printf 'Error - %s\n' "${_message}" >&2
-	fi
+    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+        printf 'Error - %s\n' "${_message}" >&2
+    fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -52,16 +52,16 @@ _git_path="${HOME}/git/${_repo_name}"
 
 
 if ((_help)) || ((_exit_status)); then
-	usage "${_exit_status}"
-	exit "${_exit_status}"
+    usage "${_exit_status}"
+    exit "${_exit_status}"
 elif ((_license)); then
-	__license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
-	exit 0
+    __license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
+    exit 0
 fi
 
 if [ -z "${_repo_name}" ]; then
-	usage 'missing repository name argument!'
-	exit "1"
+    usage 'missing repository name argument!'
+    exit "1"
 fi
 
 
diff --git a/git_shell_commands/www-set-permissions b/git_shell_commands/www-set-permissions
--- a/git_shell_commands/www-set-permissions
+++ b/git_shell_commands/www-set-permissions
@@ -2,7 +2,7 @@
 
 __SOURCE__="${BASH_SOURCE[0]}"
 while [[ -h "${__SOURCE__}" ]]; do
-	__SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
+    __SOURCE__="$(find "${__SOURCE__}" -type l -ls | sed -n 's@^.* -> \(.*\)@\1@p')"
 done
 __DIR__="$(cd -P "$(dirname "${__SOURCE__}")" && pwd)"
 __NAME__="${__SOURCE__##*/}"
@@ -18,9 +18,9 @@ source "${__DIR__}/shared_functions/license"
 
 
 usage(){
-	_message="${1}"
-	_repo_name="${_repo_name:-repository-name}"
-	cat <<EOF
+    _message="${1}"
+    _repo_name="${_repo_name:-repository-name}"
+    cat <<EOF
 ## Usage
 # ssh ${USER}@host-or-ip ${__NAME__} ${_git_args[@]:-$_repo_name}
 #
@@ -33,12 +33,12 @@ usage(){
 # -l --license
 # Shows script or project license then exits
 #
-# -h	--help help
+# -h    --help help
 #  Displays this message and exits
 EOF
-	if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
-		printf 'Error - %s\n' "${_message}" >&2
-	fi
+    if [ -n "${_message}" ] && [[ "${_message}" != '0' ]]; then
+        printf 'Error - %s\n' "${_message}" >&2
+    fi
 }
 
 _args=("${@:?# No arguments provided try: ${__NAME__} help}")
@@ -49,16 +49,16 @@ argument_parser '_args' '_valid_args'
 _exit_status="$?"
 
 if ((_help)) || ((_exit_status)); then
-	usage "${_exit_status}"
-	exit "$?"
+    usage "${_exit_status}"
+    exit "$?"
 elif ((_license)); then
-	__license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
-	exit 0
+    __license__ "${__DESCRIPTION__}" "${__AUTHOR__}"
+    exit 0
 fi
 
 if [ -z "${_repo_name}" ]; then
-	usage 'missing repository name argument!'
-	exit "1"
+    usage 'missing repository name argument!'
+    exit "1"
 fi
 
 _www="${HOME}/www"
@@ -66,15 +66,15 @@ _www_group="$(groups ${USER} | grep -oE 'www[-a-z]{0,29}')"
 _srv_path="${_www}/${_repo_name,,}"
 
 if [ -z "${_www_group}" ]; then
-	printf '# No www group found for %s\n' "${USER}"
-	exit 1
+    printf '# No www group found for %s\n' "${USER}"
+    exit 1
 fi
 if ! [ -d "${_www}" ]; then
-	printf '# No www directory at %s\n' "${_www}"
-	if [ -e "${HOME}/git-shell-commands/jekyll-build"]; then
-		printf '# try: ssh %s@host-or-ip jekyll-build %s\n' "${USER}" "${_repo_name}"
-	fi
-	exit 1
+    printf '# No www directory at %s\n' "${_www}"
+    if [ -e "${HOME}/git-shell-commands/jekyll-build"]; then
+        printf '# try: ssh %s@host-or-ip jekyll-build %s\n' "${USER}" "${_repo_name}"
+    fi
+    exit 1
 fi
 
 chown --recursive "${USER}":"${_www_group}" "${_srv_path}"
